In [1]:
# #import binary tree library
# from binarytree import Node
# from binarytree import tree
# test_bin_lib_tree = tree(height=3, is_perfect=False)
# print(test_bin_lib_tree)

In [9]:
#Import scikit-learn dataset library
from sklearn import datasets

#Load dataset
iris = datasets.load_iris()

In [3]:
# print the label species(setosa, versicolor,virginica)
print(iris.target_names)

# print the names of the four features
print(iris.feature_names)

['setosa' 'versicolor' 'virginica']
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [4]:
# print the iris data (top 5 records)
print(iris.data[0:5])

# print the iris labels (0:setosa, 1:versicolor, 2:virginica)
print(iris.target)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [10]:
# Creating a DataFrame of given iris dataset.
import pandas as pd
data=pd.DataFrame({
    'sepal length':iris.data[:,0],
    'sepal width':iris.data[:,1],
    'petal length':iris.data[:,2],
    'petal width':iris.data[:,3],
    'species':iris.target
})
data.head()

sepal length  sepal width  petal length  petal width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [11]:
# Import train_test_split function
from sklearn.model_selection import train_test_split

X=data[['sepal length', 'sepal width', 'petal length', 'petal width']]  # Features
y=data['species']  # Labels

# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3) # 70% training and 30% test

In [12]:
len(X_train)

105

In [7]:
#Import Random Forest Model
from sklearn.ensemble import RandomForestClassifier

#Create a Gaussian Classifier
clf=RandomForestClassifier(n_estimators=100)

#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(X_train,y_train)

y_pred=clf.predict(X_test)

In [8]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.9777777777777777


In [8]:
from sklearn import tree as tree_plot
import matplotlib

def print_tree(tree):
    for i in range(len(tree.estimators_)):
        print("Tree",i,'-----------------------------------------------------------------------------------')
        print("Number of nodes: ", tree.estimators_[i].tree_.node_count) #Number of node
        print("array of left children: ", tree.estimators_[i].tree_.children_left) #array of left children
        print("array of right children: ", tree.estimators_[i].tree_.children_right) #array of right children
#         print("array of nodes splitting feature: ", tree.estimators_[i].tree_.feature) #array of nodes splitting feature
#         print("array of nodes splitting points: ", tree.estimators_[i].tree_.threshold) #array of nodes splitting points
#         print("array of nodes values: ", tree.estimators_[i].tree_.value) #array of nodes values

# tree_pred = clf.estimators_[0].predict(X_test.values)
# print('X_test: ',X_test)
# print('Y_pred: ',tree_pred)
# tree_plot.plot_tree(clf.estimators_[0], class_names=True)


# def bin_tree_gen(dtree, node):
#     if dtree.children_left[node.value] == dtree.children_right[node.value]:
#         return
#     node.left = Node(dtree.children_left[node.value].item())
#     node.right = Node(dtree.children_right[node.value].item())
#     bin_tree_gen(dtree, node.left)
#     bin_tree_gen(dtree, node.right)


# root = Node(0)

# print(root)

In [9]:
print_tree(clf)

Tree 0 -----------------------------------------------------------------------------------
Number of nodes:  11
array of left children:  [ 1  2 -1 -1  5  6 -1  8 -1 -1 -1]
array of right children:  [ 4  3 -1 -1 10  7 -1  9 -1 -1 -1]
Tree 1 -----------------------------------------------------------------------------------
Number of nodes:  13
array of left children:  [ 1  2 -1 -1  5  6  7  8 -1 -1 -1 -1 -1]
array of right children:  [ 4  3 -1 -1 12 11 10  9 -1 -1 -1 -1 -1]
Tree 2 -----------------------------------------------------------------------------------
Number of nodes:  7
array of left children:  [ 1  2 -1  4 -1 -1 -1]
array of right children:  [ 6  3 -1  5 -1 -1 -1]
Tree 3 -----------------------------------------------------------------------------------
Number of nodes:  13
array of left children:  [ 1 -1  3  4  5 -1  7  8 -1 -1 -1 -1 -1]
array of right children:  [ 2 -1 12 11  6 -1 10  9 -1 -1 -1 -1 -1]
Tree 4 --------------------------------------------------------------

In [16]:
import time

accum = 0
for n in range(100):
    start_time = time.time()
    for i in range(25):
        clf.estimators_[i].predict(X_test.values[0:4])
    end_time = time.time()
    accum += end_time - start_time

print(accum/100)

0.00454888105392456


In [18]:
X_test.values[0:4]

array([[4.9, 3.6, 1.4, 0.1],
       [5.8, 2.7, 4.1, 1. ],
       [4.6, 3.2, 1.4, 0.2],
       [6.4, 2.7, 5.3, 1.9]])

In [10]:
clf.decision_path(X_test)

(<45x1426 sparse matrix of type '<class 'numpy.int64'>'
 	with 15110 stored elements in Compressed Sparse Row format>,
 array([   0,   11,   24,   31,   44,   63,   80,   95,  118,  131,  144,
         159,  166,  177,  194,  207,  220,  237,  246,  253,  266,  277,
         288,  299,  308,  329,  340,  355,  370,  385,  400,  417,  428,
         441,  456,  471,  480,  495,  506,  521,  532,  549,  570,  587,
         600,  613,  626,  643,  656,  669,  682,  695,  708,  713,  720,
         729,  742,  761,  776,  797,  810,  829,  848,  863,  878,  891,
         906,  923,  936,  955,  970,  979, 1000, 1019, 1038, 1057, 1068,
        1085, 1098, 1109, 1128, 1137, 1146, 1165, 1178, 1189, 1206, 1223,
        1230, 1241, 1254, 1265, 1284, 1299, 1314, 1331, 1342, 1355, 1372,
        1405, 1426]))

In [8]:
import numpy as np
print(clf.estimators_[0].tree_.threshold[0])
print(type(np.float16(clf.estimators_[0].tree_.threshold[0]).item()))

NameError: name 'clf' is not defined

In [2]:
def float_bin(my_number, places = 3):
    my_whole, my_dec = str(my_number).split(".")
    my_whole = int(my_whole)
    res = (str(bin(my_whole))+".").replace('0b','')
 
    for x in range(places):
        my_dec = str('0.')+str(my_dec)
        temp = '%1.20f' %(float(my_dec)*2)
        my_whole, my_dec = temp.split(".")
        res += my_whole
    return res
 
 
 
def float16_bin_IEEE754(n) :
    # identifying whether the number
    # is positive or negative
    sign = 0
    if n < 0 :
        sign = 1
        n = n * (-1)
    p = 15
    # convert float to binary
    dec = float_bin (n, places = p)

    dotPlace = dec.find('.')
    onePlace = dec.find('1')
    # finding the mantissa
    if onePlace > dotPlace:
        dec = dec.replace(".","")
        onePlace -= 1
        dotPlace -= 1
    elif onePlace < dotPlace:
        dec = dec.replace(".","")
        dotPlace -= 1
    mantissa = dec[onePlace+1:]
 
    # calculating the exponent(E)
    exponent = dotPlace - onePlace
    exponent_bits = exponent + 15
 
    # converting the exponent from
    # decimal to binary
    exponent_bits = bin(exponent_bits).replace("0b",'')
 
    mantissa = mantissa[0:10]
 
    # the IEEE754 notation in binary    
    final = str(sign) + exponent_bits.zfill(5) + mantissa
 
    # convert the binary to hexadecimal
    hstr = '0x%0*X' %((len(final) + 3) // 4, int(final, 2))
    return (hstr, final)

def bin_float16_IEEE754(bin):
    sign = (-1)**int(bin[0])
    exponent = int(bin[1:6],2)-15
    fraction = 0.0
    for i in range(6,16):
        fraction = fraction + int(bin[i])*(2**(5-i))
    res = sign*(1+fraction)*(2**exponent)
    return res



(hex16,bin16) = float16_bin_IEEE754(9.132)
float16 = bin_float16_IEEE754(bin16)
print (hex16)
print (float16)


0x4890
9.125


In [3]:
BRAM_DWIDTH      = 40
BRAM_AWIDTH      = 14

TREE_DEPTH       = 13 # number of levels
LEAF_IDX         = 0
THSH_IDX         = 1
THSH_WIDTH       = 16
ATTR_IDX         = 17
ATTR_WIDTH       = 5
RCHLD_IDX        = 22
RCHLD_WIDTH      = BRAM_DWIDTH - ATTR_WIDTH - THSH_WIDTH - 1
LAST_IDX         = 1
RES_IDX          = 2
RES_WIDTH        = 16
TREE_IDX         = 18
TREE_WIDTH       = BRAM_DWIDTH - RES_WIDTH - 2

LAST_AB_IDX      = 0
AB_TREE_IDX      = 1
AB_TREE_WIDTH    = BRAM_AWIDTH

In [4]:
import numpy as np
def split(a, n):
    k, m = divmod(len(a), n)
    return (a[i*k+min(i, m):(i+1)*k+min(i+1, m)] for i in range(n))
def tree_bram_gen(dtree_list, no_parts, tree_bram):
    div_tree_list = list(split(dtree_list,no_parts))
    
    absolute_idx = 0
    for dtp_tree in div_tree_list:
        for tree in dtp_tree:
            if dtp_tree.index(tree) == 0:
                absolute_addr = no_parts + len(tree_bram) - absolute_idx
                if absolute_idx == no_parts-1:
                    absolute_addr_bin = ("{0:0"+str(BRAM_DWIDTH-1)+"b}").format(absolute_addr) + '1'
                else:
                    absolute_addr_bin = ("{0:0"+str(BRAM_DWIDTH-1)+"b}").format(absolute_addr) + '0'
                tree_bram.insert(absolute_idx,absolute_addr_bin)
                absolute_idx = absolute_idx + 1
                
            dtree = tree.tree_
            is_last = (tree == dtp_tree[-1])
            for node_idx in range(dtree.node_count):
                is_leaf = dtree.children_left[node_idx] == dtree.children_right[node_idx]

                if bool(is_leaf) is True:
                    result = np.argmax(dtree.value[node_idx]).item()
                    next_tree = dtree.node_count - node_idx

                    result_bin = ("{0:0"+str(RES_WIDTH)+"b}").format(result)
                    next_tree_bin = ("{0:0"+str(TREE_WIDTH)+"b}").format(next_tree)
                    is_leaf_bin = "{0:01b}".format(int(is_leaf))
                    is_last_bin = "{0:01b}".format(int(is_last))

                    bram_node = next_tree_bin[0:TREE_WIDTH] + result_bin[0:RES_WIDTH] + is_last_bin[0] + is_leaf_bin[0]
                else:
                    right_child_addr = dtree.children_right[node_idx].item() - node_idx - 1
                    threshold = dtree.threshold[node_idx].item()
                    attribute = dtree.feature[node_idx].item()

                    right_child_addr_bin = ("{0:0"+str(RCHLD_WIDTH)+"b}").format(right_child_addr)
                    (_ ,threshold_bin) = float16_bin_IEEE754(threshold)
                    attribute_bin = ("{0:0"+str(ATTR_WIDTH)+"b}").format(attribute)
                    is_leaf_bin = "{0:01b}".format(int(is_leaf))

                    bram_node = right_child_addr_bin[0:RCHLD_WIDTH] + attribute_bin[0:ATTR_WIDTH] + threshold_bin[0:THSH_WIDTH] + is_leaf_bin[0]
                tree_bram.append(bram_node)
                

In [5]:
bram = []
trees = clf.estimators_[0:25]
parts = 5
tree_bram_gen(dtree_list=trees, no_parts=parts, tree_bram=bram)
print(bram)

['0000000000000000000000000000000000001010', '0000000000000000000000000000000010001000', '0000000000000000000000000000000100101010', '0000000000000000000000000000000110101000', '0000000000000000000000000000001000011111', '0000000000000000110001001000100110000000', '0000000000000000010001100111010011001100', '0000000000000000001001000000000000000001', '0000000000000000001000000000000000000101', '0000000000000001010000001000110000011000', '0000000000000000010001001000101000011000', '0000000000000000000101000000000000001001', '0000000000000000010001100111111000000000', '0000000000000000000011000000000000000101', '0000000000000000000010000000000000001001', '0000000000000000000001000000000000001001', '0000000000000000110001001000100110000000', '0000000000000000010001001000001001100110', '0000000000000000001011000000000000000001', '0000000000000000001010000000000000000101', '0000000000000001110001100111110110011000', '0000000000000001010001001000101010110010', '000000000000000011000000100011

In [6]:
def rambin2ramdec(rambin, no_parts, ramdec):
    node_addr = 0
    for node in rambin:
        node_dict = {}
        if rambin.index(node) < no_parts:
            node_dict['is_last_absolute_addr'] = bool(int(node[(BRAM_DWIDTH-1)]))
            node_dict['absolute_addr'] = int(node[0:(BRAM_DWIDTH-1)],2)
        elif int(node[BRAM_DWIDTH-1]) == 1:
            node_dict['is_leaf'] = True
            node_dict['is_last'] = bool(int(node[(BRAM_DWIDTH-1)-LAST_IDX]))
            node_dict['result'] = int(node[(BRAM_DWIDTH-1)-(RES_IDX+RES_WIDTH-1):(BRAM_DWIDTH-1)-RES_IDX+1],2)
            node_dict['next_tree'] = int(node[(BRAM_DWIDTH-1)-(TREE_IDX+TREE_WIDTH-1):(BRAM_DWIDTH-1)-TREE_IDX+1],2)
        else:
            node_dict['is_leaf'] = False
            node_dict['right_child'] = int(node[(BRAM_DWIDTH-1)-(RCHLD_IDX+RCHLD_WIDTH-1):(BRAM_DWIDTH-1)-RCHLD_IDX+1],2)
            thres = node[(BRAM_DWIDTH-1)-(THSH_IDX+THSH_WIDTH-1):(BRAM_DWIDTH-1)-THSH_IDX+1]
            #node_dict['threshold'] = '0x%0*X' %((len(thres) + 3) // 4, int(thres, 2))
            #node_dict['threshold'] += ' - ' +  str(bin_float16_IEEE754(thres))
            node_dict['threshold'] = bin_float16_IEEE754(thres)
            node_dict['attribute'] = int(node[(BRAM_DWIDTH-1)-(ATTR_IDX+ATTR_WIDTH-1):(BRAM_DWIDTH-1)-ATTR_IDX+1],2)
        ramdec.append(node_dict)

In [7]:
dec_ram = []
rambin2ramdec(bram, parts, dec_ram)

tree_idx = 0
dtp_idx = 0
print(("Tree "+str(tree_idx)).center(120, "-"))
print(("PART "+str(dtp_idx)).center(120, "*"))
for i in range(len(dec_ram)):
    print("addr ",i,": ", dec_ram[i])
    
    if 'is_leaf' in dec_ram[i]:
        if dec_ram[i]['is_leaf'] == True:
            if dec_ram[i]['next_tree'] == 1:
                tree_idx = tree_idx+1
                print(("Tree "+str(tree_idx)).center(120, "-"))
                if dec_ram[i]['is_last'] == True:
                    dtp_idx = dtp_idx+1
                    print(("PART "+str(dtp_idx)).center(120, "*"))

---------------------------------------------------------Tree 0---------------------------------------------------------
*********************************************************PART 0*********************************************************
addr  0 :  {'is_last_absolute_addr': False, 'absolute_addr': 5}
addr  1 :  {'is_last_absolute_addr': False, 'absolute_addr': 68}
addr  2 :  {'is_last_absolute_addr': False, 'absolute_addr': 149}
addr  3 :  {'is_last_absolute_addr': False, 'absolute_addr': 212}
addr  4 :  {'is_last_absolute_addr': True, 'absolute_addr': 271}
addr  5 :  {'is_leaf': False, 'right_child': 3, 'threshold': 4.75, 'attribute': 2}
addr  6 :  {'is_leaf': False, 'right_child': 1, 'threshold': 0.7998046875, 'attribute': 3}
addr  7 :  {'is_leaf': True, 'is_last': False, 'result': 0, 'next_tree': 9}
addr  8 :  {'is_leaf': True, 'is_last': False, 'result': 1, 'next_tree': 8}
addr  9 :  {'is_leaf': False, 'right_child': 5, 'threshold': 6.046875, 'attribute': 0}
addr  10 :  {'is_le

In [13]:
def tree_coeff_file_gen(rambin, filename):
    f = open(filename+'.coe', "w")
    f.write("memory_initialization_radix=16;\n")
    f.write("memory_initialization_vector=")
    for node in rambin:
        hex_str = ('0x%0*X' %((len(node) + 3) // 4, int(node, 2)))+' '
        print(hex_str)
        f.write(hex_str[2:None])
    f.write(";\n")
    f.close()
    
tree_coeff_file_gen(bram, 'test')

0x000000000A 
0x0000000088 
0x000000012A 
0x00000001A8 
0x000000021F 
0x0000C48980 
0x00004674CC 
0x0000240001 
0x0000200005 
0x0001408C18 
0x0000448A18 
0x0000140009 
0x0000467E00 
0x00000C0005 
0x0000080009 
0x0000040009 
0x0000C48980 
0x0000448266 
0x00002C0001 
0x0000280005 
0x0001C67D98 
0x0001448AB2 
0x0000C08C4C 
0x00004281CC 
0x0000140009 
0x0000100005 
0x00000C0005 
0x0000080009 
0x0000040009 
0x0001467E00 
0x0000448266 
0x0000140001 
0x0000448A18 
0x00000C0005 
0x0000080009 
0x0000040009 
0x00004482CC 
0x0000300001 
0x0002467E00 
0x0001C48AB2 
0x00004489E6 
0x0000200005 
0x0000C08CB2 
0x0000467C66 
0x0000140009 
0x0000100005 
0x00000C0005 
0x0000080009 
0x0000040009 
0x0000448266 
0x0000480003 
0x0002C48A18 
0x0000448980 
0x00003C0007 
0x0001C08D00 
0x0001428466 
0x0000408C80 
0x00002C000B 
0x0000467D32 
0x0000240007 
0x000020000B 
0x00001C0007 
0x0000180007 
0x0000C08C32 
0x0000467D98 
0x00000C0007 
0x000008000B 
0x000004000B 
0x00004674CC 
0x0000400001 
0x0002467E00 
0x0000

In [14]:
def attribute_coeff_file_gen(sample, filename):
    f = open(filename+'.coe', "w")
    f.write("memory_initialization_radix=16;\n")
    f.write("memory_initialization_vector=")
    
    for attr in sample:
        (attr_hex, _) = float16_bin_IEEE754(attr.item())
        f.write(attr_hex[2:None]+' ')
    f.write(';')
        
attribute_coeff_file_gen(X_test.values[0], 'attr_test')

def attribute_hex_convert(sample_list):
    for sample in sample_list:
        for attr in sample:
            (attr_hex, _) = float16_bin_IEEE754(attr.item())
            print('16\'h'+attr_hex[2:None]+', ',end = "")
        print('\n')
        
attribute_coeff_file_gen(X_test.values[0], 'attr_test')
attribute_hex_convert(X_test.values)

16'h454C, 16'h4366, 16'h3E00, 16'h3266, 

16'h45B3, 16'h4200, 16'h4433, 16'h3CCC, 

16'h44E6, 16'h4200, 16'h3D99, 16'h3266, 

16'h4599, 16'h41CC, 16'h4333, 16'h3D33, 

16'h47B3, 16'h4199, 16'h46B3, 16'h4000, 

16'h4499, 16'h4333, 16'h3C00, 16'h3266, 

16'h45B3, 16'h4399, 16'h3ECC, 16'h34CC, 

16'h47B3, 16'h4133, 16'h46E6, 16'h4099, 

16'h4500, 16'h4099, 16'h4299, 16'h3C00, 

16'h4466, 16'h41CC, 16'h3D99, 16'h3266, 

16'h47E6, 16'h4399, 16'h4666, 16'h4000, 

16'h4633, 16'h42CC, 16'h4566, 16'h4099, 

16'h44B3, 16'h4266, 16'h3E66, 16'h3266, 

16'h44E6, 16'h4233, 16'h3E00, 16'h3266, 

16'h4600, 16'h4166, 16'h4519, 16'h3E66, 

16'h4733, 16'h4266, 16'h4600, 16'h3F33, 

16'h464C, 16'h4100, 16'h44E6, 16'h3E00, 

16'h46CC, 16'h4200, 16'h4580, 16'h4033, 

16'h4599, 16'h4100, 16'h43CC, 16'h3C66, 

16'h46E6, 16'h4233, 16'h4519, 16'h4099, 

16'h4566, 16'h43CC, 16'h3ECC, 16'h3666, 

16'h464C, 16'h42CC, 16'h4599, 16'h40CC, 

16'h4480, 16'h4099, 16'h3D33, 16'h34CC, 

16'h464C, 16'h4199, 16'h4519, 16'h

In [15]:
X_test.values[0]
list(X_test.values[0])

[5.3, 3.7, 1.5, 0.2]

In [17]:
from sklearn import metrics
def decision_path(sample, ramdec, start_idx, class_accum):
    idx = start_idx
    while True:
        print(idx)
        if ramdec[idx]['is_leaf'] == True:
#             print(idx)
            class_accum[ramdec[idx]['result']] += 1
            if ramdec[idx]['is_last'] ==  True: 
                return
            idx += ramdec[idx]['next_tree']
        else:
            if sample[ramdec[idx]['attribute']] <= ramdec[idx]['threshold']:
                idx += 1
            else:
                idx += ramdec[idx]['right_child'] + 1
                
def decision_path_bram(sample_list, ramdec, n_classes, result):
    s_idx = 0
    for sample in sample_list:
        print('Sample',s_idx,'****************************************************************************')
        accum_result = [0]*n_classes
        for node_idx in range(len(ramdec)):
            print('Stage', node_idx, '------------------------------------------')
            decision_path(sample, ramdec, int(ramdec[node_idx]['absolute_addr']), accum_result)
            
            if ramdec[node_idx]['is_last_absolute_addr'] == True:
                break
        result.append(accum_result.index(max(accum_result)))
        s_idx+=1

def accuracy_cal(pred, true):
    n_correct = 0
    for i in range(len(pred)):
        if pred[i] == true[i]:
            n_correct+=1
    return n_correct/len(pred)
        
out_pred=[]
test_list = [ [6.0, 3.4, 4.5, 1.6], 
              [4.9, 3.6, 1.4, 0.1], 
              [5.6, 2.9, 3.6, 1.3], 
              [5.6, 2.5, 3.9, 1.1] ]


# decision_path_bram(list(X_test.values), dec_ram, 3, out_pred)
decision_path_bram(test_list, dec_ram, 3, out_pred)
print("Accuracy:",metrics.accuracy_score(clf.predict(X_test), np.array(out_pred)))



Sample 0 ****************************************************************************
Stage 0 ------------------------------------------
5
6
8
16
17
19
29
30
32
33
36
38
39
40
41
49
51
52
53
Stage 1 ------------------------------------------
68
70
71
73
74
78
85
87
88
100
106
116
117
119
120
123
125
126
136
138
139
140
Stage 2 ------------------------------------------
149
151
152
164
165
167
168
171
175
176
177
182
184
185
186
188
199
201
202
203
Stage 3 ------------------------------------------
212
214
215
216
225
227
228
234
235
242
244
245
251
252
254
255
258
260
261
262
Stage 4 ------------------------------------------
271
273
274
275
282
286
287
293
295
296
300
302
304
306
307
308
313
317
318
320
321
Sample 1 ****************************************************************************
Stage 0 ------------------------------------------
5
6
7
16
17
18
29
30
31
36
37
49
50
Stage 1 ------------------------------------------
68
69
85
86
100
101
102
123
124
136
137
Stage 2 ----------

NameError: name 'X_test' is not defined

In [1]:
import joblib

# save
joblib.dump(clf, "random_forest.joblib")

NameError: name 'clf' is not defined

In [1]:
import joblib
clf = joblib.load("./random_forest.joblib")

# for i in range(len(loaded_clf.estimators_)):
#     print("Tree",i,'-----------------------------------------------------------------------------------')
#     print("Number of nodes: ", loaded_clf.estimators_[i].tree_.node_count) #Number of node
#     print("array of left children: ", loaded_clf.estimators_[i].tree_.children_left) #array of left children
#     print("array of right children: ", loaded_clf.estimators_[i].tree_.children_right) #array of right children
#     print("array of nodes splitting feature: ", loaded_clf.estimators_[i].tree_.feature) #array of nodes splitting feature
#     print("array of nodes splitting points: ", loaded_clf.estimators_[i].tree_.threshold) #array of nodes splitting points
#     print("array of nodes values: ", loaded_clf.estimators_[i].tree_.value) #array of nodes values